Quizzes/Controllers/AnswerController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Quizzes.Data;
using Quizzes.Data.Model;

namespace Quizzes.Controllers
{
	public class AnswerController:Controller
	{
		private readonly AppDBContext context;

		public AnswerController(AppDBContext context)
		{
			this.context = context;
		}

		public IActionResult Add(int id)
		{
			var answer = new Answer() { QuestionId = id };
			return View(answer);
		}

		[Route("Answer/Edit/{id}")]
		public IActionResult Edit(int id)
		{
			var answer = context.Answers.AsNoTracking().First(a => a.Id == id & !a.IsDel);
			return View(answer);
		}

		[Route("Answer/Edit")]
		[Route("Answer/Edit/{id}")]
		[HttpPost]
		public IActionResult Edit(int id,Answer answer)
		{
			if (ModelState.IsValid)
			{
				if (answer.Id == 0)
				{
					context.Answers.Add(answer);
					context.SaveChanges();
					return RedirectToAction("Edit","Question", new { id = answer.QuestionId });
				}
				context.Update(answer);
				context.SaveChanges();
			}
			return View(answer);
		}


		public IActionResult Del(int id)
		{
			var elem = context.Answers.AsNoTracking().First(p => p.Id == id);
			elem.IsDel = true;
			context.Update(elem);
			context.SaveChanges();
			return RedirectToAction("Edit", "Question", new { id = elem.QuestionId });
		}
	}
}

Quizzes/Views/Answer/Add.cshtml
@model Answer
<div class="row">
	<h3>Add Answer</h3>
	<form asp-controller="Answer" asp-action="Edit" enctype="multipart/form-data" method="post" class="form-horizontal">
		<br />
		<br />
		<div type="hidden" class="form-group">
			<div type="hidden" class="col-md-5">
				<input type="hidden" asp-for="QuestionId" class="from-control" />
				<span type="hidden" asp-validation-for="QuestionId" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Text"></label>
			<input asp-for="Text" class="from-control" />
			<span asp-validation-for="Text" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="True"></label>
			<input asp-for="True" class="from-control" />
			<span asp-validation-for="True" class="text-danger"></span>
		</div><br/>
		<input class="btn btn-success" type="submit" value="Add Answer" />
	</form>
</div>

Quizzes/Views/Answer/Edit.cshtml
@model Answer
<div class="row">
	<h3>Edit Answer</h3>
	<form asp-controller="Answer" asp-action="Edit" enctype="multipart/form-data" method="post" class="form-horizontal">
		<br />
		<br />
		<div type="hidden" class="form-group">
			<div type="hidden" class="col-md-5">
				<input type="hidden" asp-for="Id" class="from-control" />
				<span type="hidden" asp-validation-for="Id" class="text-danger"></span>
			</div>
		</div>
		<div type="hidden" class="form-group">
			<div type="hidden" class="col-md-5">
				<input type="hidden" asp-for="QuestionId" class="from-control" />
				<span type="hidden" asp-validation-for="QuestionId" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Text"></label>
			<input asp-for="Text" class="from-control" />
			<span asp-validation-for="Text" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="True"></label>
			<input asp-for="True" class="from-control" />
			<span asp-validation-for="True" class="text-danger"></span>
		</div><br />
		<a class="btn btn-warning" asp-controller="Question" asp-action="Edit" asp-route-id="@Model.QuestionId">Back to Questions</a>
		<input class="btn btn-success" type="submit" asp-route-id="@Model.Id" value="Save Changes" />
	</form>
</div>