Quizzes/Controllers/ResultController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Quizzes.Data;
using Quizzes.Data.Model;
using Quizzes.ViewModels;

namespace Quizzes.Controllers
{
	public class ResultController:Controller
	{
		private readonly AppDBContext context;

		public ResultController(AppDBContext context)
		{
			this.context = context;
		}

		public IActionResult CheckAnswers(string url, string user)
		{
			var urlTest = context.UrlTests.AsNoTracking().First(a => a.Url == url);
			var test = context.Tests.AsNoTracking().First(a => a.Id == urlTest.TestId);
			var questions = context.Questions.AsNoTracking().Where(a => a.TestId == test.Id & !a.IsDel);
			var urlTestAttends = context.UrlTestAttends.AsNoTracking().Where(a => a.UrlTestUrl == url)
				.OrderBy(a => a.NumberOfRun).ToList();
			var obj = new UrlAttendsViewModel()
				{ Name = urlTest.Name, User = user, MaxPoint = questions.Count(), UrlTestAttends = urlTestAttends };
			return View(obj);
		}

		[Route("Result/CheckTest/{testAttemptId}")]
		public IActionResult CheckTest(int testAttemptId)
		{
			var urlTestAttend = context.UrlTestAttends.AsNoTracking().First(a => a.Id == testAttemptId);
			var score = 0;
			var results = context.Results.AsNoTracking().Where(a => a.UrlTestAttendId == urlTestAttend.Id).ToList();
			var urlTest = context.UrlTests.AsNoTracking().First(a => a.Url == urlTestAttend.UrlTestUrl);
			var test = context.Tests.AsNoTracking().First(a => a.Id == urlTest.TestId & !a.IsDel);
			var questions = context.Questions.AsNoTracking().Where(a => a.TestId == test.Id & !a.IsDel)
				.OrderBy(a => a.Id).ToList();
			var answers = new List<Answer>();

			foreach (var result in results)
			{
				answers.Add(context.Answers.AsNoTracking().First(a => a.Id == result.AnswerId));
			}

			foreach (var question in questions)
			{
				var answersBase = context.Answers.AsNoTracking().Where(a => a.QuestionId == question.Id & !a.IsDel).ToList();
				var answerQuestion = answers.Where(a => a.QuestionId == question.Id).ToList();
				var trueAnswer = true;
				var trueAnswerCount = 0;
				foreach (var answer in answersBase)
					if (answer.True)
						trueAnswerCount++;

				if (trueAnswerCount == answerQuestion.Count)
				{
					foreach (var answer in answerQuestion)
						if (!answer.True)
						{
							trueAnswer = false;
							break;
						}
				}
				else
					trueAnswer = false;

				if (trueAnswer)
				{
					score++;
				}
			}


			urlTestAttend.Point = score;
			context.Update(urlTestAttend);
			context.SaveChanges();
			var urlResult = new UrlResultViewModel()
			{
				Url = urlTest.Url,
				Name = urlTest.Name,
				Point = urlTestAttend.Point,
				MaxPoint = questions.Count,
				NumberOfRun = urlTestAttend.NumberOfRun,
				TestTime = urlTestAttend.TestTime
			};
			return View(urlResult);
		}
	}
}

Quizzes/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Quizzes.Data;
using Quizzes.Data.Model;
using Quizzes.ViewModels;

namespace Quizzes.Controllers
{
	public class TestController:Controller
	{
		
		private readonly AppDBContext context;

		public TestController(AppDBContext context)
		{
			this.context = context;
		}

		public IActionResult Add()
		{
			return View();
		}

		[Route("Test/Edit/{id}")]
		public IActionResult Edit(int id)
		{
			var testBase = context.Tests.AsNoTracking().First(a => a.Id == id & !a.IsDel);
			var obg = new TestUpdatedViewModel
			{
				Test = testBase,
				Questions = context.Questions.AsNoTracking().Where(a => a.TestId == id & !a.IsDel).ToList(),
				ImgDel = "/img/Delete.jpg",
				ImgEdit = "/img/Edit.jpg"
			};
			return View(obg);
		}

		[Route("Test/Edit")]
		[Route("Test/Edit/{id}")]
		[HttpPost]
		public IActionResult Edit(int id, TestUpdatedViewModel testModel)
		{

			if (testModel.Test.Id == 0)
			{
				context.Tests.Add(testModel.Test);
				context.SaveChanges();
				return RedirectToAction("Admin", "Admin");
			}

			context.Update(testModel.Test);
			context.SaveChanges();


			testModel.Test = context.Tests.AsNoTracking().FirstOrDefault(a => a.Id == testModel.Test.Id & !a.IsDel);
			testModel.Questions = context.Questions.AsNoTracking()
				.Where(a => a.TestId == testModel.Test.Id & !a.IsDel).ToList();
			testModel.ImgDel = "/img/Delete.jpg";
			testModel.ImgEdit = "/img/Edit.jpg";
			return View(testModel);
		}

		public IActionResult Del(int id)
		{
			var elem = context.Tests.AsNoTracking().First(p => p.Id == id);
			elem.IsDel = true;
			context.Update(elem);
			context.SaveChanges();
			return RedirectToAction("Admin","Admin");
		}

	}
}

Quizzes/Views/Admin/AddUrlTest.cshtml
@model UrlTest
<div class="row">
	<h3>Add Url</h3>
	<form asp-action="AddUrlTest" enctype="multipart/form-data" method="post" class="form-horizontal">
		<br />
		<br />
		<div type="hidden" class="form-group">
			<div type="hidden" class="col-md-5">
				<input type="hidden" asp-for="TestId" class="from-control" />
				<span type="hidden" asp-validation-for="TestId" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Time"></label>
			<input asp-for="Time" class="from-control">
			<span asp-validation-for="Time" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="NumberOfRuns"></label>
			<input asp-for="NumberOfRuns" class="from-control" />
			<span asp-validation-for="NumberOfRuns" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Url"></label>
			<input asp-for="Url" class="from-control" />
			<span asp-validation-for="Url" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="from-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div><br/>
		<input class="btn btn-success" type="submit" value="Add Url" />
	</form>
</div>

Quizzes/Views/Admin/AddUrlTestUrl.cshtml
@model UrlTest
<h1>https://localhost:44336/UserTest/Start/@Model.Url</h1>
<h2><a class="btn btn-warning" asp-controller="Admin" asp-action="Admin">Admin</a></h2>

Quizzes/Views/Admin/Admin.cshtml
@model AdminTestViewModel
<div>
	<h1>Hello @Model.Admin.Name</h1>
	<a class="btn btn-warning" asp-controller="Test" asp-action="Add">Add Test</a>
	<table border="1">
		@{
			var i = 1;
			foreach (var test in Model.Tests)
			{
				<tr>
					<td>@i @test.Name</td>
					<td><a asp-controller="Test" asp-action="Edit" asp-route-Id="@test.Id"><img src="@Model.ImgEdit" alt="Edit" width="30" height="30" /></a></td>
					<td><a class="btn btn-warning" asp-controller="Admin" asp-action="AllUrlTest" asp-route-Id="@test.Id">All Url</a></td>
					<td><a class="btn btn-warning" asp-controller="Admin" asp-action="AddUrlTest" asp-route-Id="@test.Id">Add Url</a></td>
					<td><a asp-controller="Test" asp-action="Del" asp-route-Id="@test.Id"><img src="@Model.ImgDel" alt="Del" width="30" height="30" /></a></td>
				</tr>
				i++;
			}
		}
	</table>
</div>

Quizzes/Views/Admin/AllUrlTest.cshtml
@model AllUrlViewModel
<div>
	<a class="btn btn-warning" asp-controller="Admin" asp-action="Admin">Admin</a>
	<table border="1">
		<tr>
			<th>№</th>
			<th>Url</th>
			<th>Runs Number</th>
			<th>Time</th>
			<th>Name</th>
			<th>CreateUrl</th>
			<th>Results</th>
		</tr>
		@{
			var i = 1;
			foreach (var url in Model.UrlTests)
			{
				<tr>
					<td>@i)</td>
					<td>https://localhost:44336/UserTest/Start/@url.Url</td>
					<td>@{
						    if (url.NumberOfRuns != null)
						    {
							    @url.NumberOfRuns
						    }
						    else
						    {
							    <strong>Max</strong>
						    }
					    }</td>
					<td>@url.Time</td>
					<td>@url.Name</td>
					<td><a class="btn btn-warning" asp-controller="Admin" asp-action="CreateUrlTest" asp-route-url="@url.Url" asp-route-user="Admin">CreateUrl</a></td>
					<td><a class="btn btn-warning" asp-controller="Result" asp-action="CheckAnswers" asp-route-url="@url.Url" asp-route-user="Admin">All Result</a></td>
				</tr>
				i++;
			}
		}
	</table>
</div>

Quizzes/Views/Admin/CreateUrlTest.cshtml
@model UrlTest
<h1>https://localhost:44336/UserTest/Start/@Model.Url</h1>
<h2><a class="btn btn-warning" asp-controller="Admin" asp-action="Admin">Admin</a></h2>

Quizzes/Views/Admin/Exit.cshtml
@model AdminViewModel
<h2>Exit</h2><br />
<div class="row">
	<form asp-action="Exit" enctype="multipart/form-data" method="post" class="form-horizontal">
		@{
			if (Model != null)
			{
				if (!string.IsNullOrEmpty(Model.Mes))
				{
					<strong>@Model.Mes</strong>
				}
			}
		}
		<br />
		<br />
		<div class="form-group">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="from-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Password"></label>
			<input asp-for="Password" class="from-control" />
			<span asp-validation-for="Password" class="text-danger"></span>
		</div>
		<input class="btn btn-success" type="submit" value="Sign in" />
	</form>
</div>